name: Pets
version: '${project.version}'
main: me.kalypso.pets.Pets
api-version: '1.20'
depend: [ProtocolLib]
commands:
  vehicles:
    description: Root command
    usage: /<command> [options]
    permission: vehicles.admin