name: Pets
version: '1.0'
main: me.kalypso.pets.Pets
api-version: '1.20'
depend: [ProtocolLib]
commands:
  pets:
    description: Root command
    usage: /<command> [options]
    permission: pets.admin